### ISSUE TITLE
Content renders over tabbar and under.

### ISSUE THREAD

**Issue by filimo** [tugayac/swiftui-custom-tab-bar-tutorial#1]
![Screen Shot 2020-01-15 at 21 04 11](https://user-images.githubusercontent.com/327296/72458909-96c34800-37da-11ea-993f-07192d7c01d3.png)

```swift
CustomTabBarItem(iconName: "star.fill",
                 label: "Favorites",
                 selection: $selection,
                 tag: 0) {
    VStack {
        ForEach(1...100, id: \.self) { _ in
            Text("Recents Content")
        }
    }
}
```

**Comment by tugayac** [comment]
@filimo have you tried using a [`ScrollView`](https://developer.apple.com/documentation/swiftui/scrollview)?

**Comment by filimo** [comment]
Thanks, ScrollView helps the problem.
